version: '3'

services:
  app:
    hostname: opennames-app
    image: 'node:14.16.0-alpine3.13'
    working_dir: /app
    ports:
      - 3000:3000/tcp
    env_file:
      - ./.env
    environment:
      # For color formatted debug messages
      - FORCE_COLOR=1
    volumes:
      - .:/app
      - ../..:/app/opennames-to-neo4j
      - opennames_minimal_node_modules:/app/node_modules
      - opennames_minimal_src_node_modules:/app/opennames-to-neo4j/node_modules
    command: ash -c "cd /app/opennames-to-neo4j && npm i && cd /app && npm i && npm run start:dev"

volumes:
  opennames_minimal_node_modules:
  opennames_minimal_src_node_modules:
