version: '3'

services:
  node:
    hostname: open-names-node
    build: ./docker/node
    env_file:
      - ./.env
    volumes:
      - ./package:/app
      - nodejs_node_modules:/app/node_modules
      - nodejs_yarn_cache:/app/.yarn/cache
      - neo4j_import:/app/data

  neo4j:
    image: neo4j:4.2.3
    hostname: open-names-neo4j
    ports:
      - 7687:7687/tcp
    environment:
      - NEO4J_AUTH=neo4j/pass
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4JLABS_PLUGINS=["apoc"]
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_directories_logs=/var/lib/neo4j/logs
    volumes:
      - ./docker/neo4j/logs:/var/lib/neo4j/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/var/lib/neo4j/plugins
      - neo4j_data:/var/lib/neo4j/data
    tty: true
    stdin_open: true

volumes:
  neo4j_import:
  neo4j_data:
  neo4j_plugins:
  nodejs_yarn_cache:
  nodejs_node_modules:
