version: '3'

services:
  dev:
    hostname: opennames-dev
    image: 'node:14.16.0-alpine3.13'
    # ports:
    #   - 3000:3000/tcp
    #   - 3003:3003/tcp
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
      - on2n4j_dev_node_modules:/app/node_modules
      - on2n4j_dev_yarn_cache:/app/.yarn/cache
    command: 'npm run start:dev'

volumes:
  on2n4j_dev_node_modules:
  on2n4j_dev_yarn_cache:
